spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/work-and-rest"
    username: "root"
    password: "12345678"
  mvc:

    hidden-method:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: "create"
        show_sql: false
  docker:
    compose:
      file: local-start/docker-compose.yml